name: mobile_app
description: Deno Application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  shared_preferences: ^0.5.0
  provider: ^4.0.2
  qrscan: ^0.2.17
  percent_indicator: ^2.1.1
  firebase_messaging: ^6.0.9
  intl: 0.15.7
  smooth_star_rating: 1.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/MobilePhoneIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/